### PR TITLE
Document workaround for pulling with table prefixes

### PR DESCRIPTION
**Pull request by xaqrox**
Quick tip for a Pantheon edge case. I'm not sure if I have the warning syntax right, or if it can handle a code block inside...

### CODE REVIEW

**Comment by reynoldsalec** [comment]
@xaqrox do you happen to have the verbatim error message handy? Might be good to include that in the warning message, particularly if Google picks it up for those looking for the solution :)

**Comment by xaqrox** [comment]
@reynoldsalec just saw your comment! I did that, and then thought, "what if the error message was more helpful" so I did that too. We could even take it a step further and make the message something like:

```sh
lando_red "Couldn't find expected tables ($PULL_DB_CHECK_TABLE)"
lando_pink "If that's the wrong table to expect, set LANDO_DB_USER_TABLE=\"your_table_name_here\" in the container's environment"
exit 1
```

**Comment by xaqrox** [comment]
Of course, I guess that makes it no-longer-googleable for folks with the original error...

**Comment by reynoldsalec** [comment]
...finally moving this along, thanks @xaqrox!

**Pull request merged**
