### PR TITLE
lando/lando#3137: Add mariadb to Pantheon integration.

### PR DESCRIPTION
**Pull request by reynoldsalec**

### CODE REVIEW

**Comment by reynoldsalec** [comment]
@pirog I think this is ready for your perusal.

One observation: When someone with an existing Lando site based on the Pantheon recipe runs `lando rebuild` after upgrading, it looks like their database volume isn't preserved (see testing steps below). I'm guessing that, in the process of swapping out their existing (Bitnami) MariaDB service with the new one, something goes wrong with remounting their old DB data in the new location (`/var/lib/mariadb`) on the virtual machine...I was kind of hoping it would just work.

Steps:

1) `lando init --source pantheon --pantheon-auth "$PANTHEON_MACHINE_TOKEN" --pantheon-site landobot-drupal8 --option composer_version=1.10.1`

2) `lando start && lando pull --code none --database dev --files dev --rsync`

3) Go to locally installed `lando/cli` and `git checkout 3209-lagoon-removal`.

4) Go to locally installed `lando/pantheon` and `git checkout 3137-mariadb`

5) Go back to project and `lando rebuild -y`

**Comment by dougchan-okta** [comment]
> One observation: When someone with an existing Lando site based on the Pantheon recipe runs lando rebuild after upgrading, it looks like their database volume isn't preserved (see testing steps below). I'm guessing that, in the process of swapping out their existing (Bitnami) MariaDB service with the new one, something goes wrong with remounting their old DB data in the new location (/var/lib/mariadb) on the virtual machine...I was kind of hoping it would just work.

As long as I've been using lando, it's been the expectation that every time there's an update, there's a chance that the db will get wiped. I don't see it as an issue, but maybe that's just me.

Thank you for your work on this! Eagerly waiting for this one to get merged. I wish I could help test, but I'm unfamiliar with the process.

**Comment by Coufu** [comment]
> One observation: When someone with an existing Lando site based on the Pantheon recipe runs lando rebuild after upgrading, it looks like their database volume isn't preserved (see testing steps below). I'm guessing that, in the process of swapping out their existing (Bitnami) MariaDB service with the new one, something goes wrong with remounting their old DB data in the new location (/var/lib/mariadb) on the virtual machine...I was kind of hoping it would just work.

As long as I've been using lando, it's been the expectation that every time there's an update, there's a chance that the db will get wiped. I don't see it as an issue, but maybe that's just me.

Thank you for your work on this! Eagerly waiting for this one to get merged. I wish I could help test, but I'm unfamiliar with the process.

**Comment by reynoldsalec** [comment]
Taking a look at usage, my guess is that our total number of Intel users is at least 50x (probably more) than our number of M1 users on Pantheon, so I think making this a breaking change for M1 users will be fine.

**Comment by reynoldsalec** [comment]
Ok, I'm checking using `process.arch`, which basically checks the Node process running Lando. This should be locked down in our distributed binary, so that shouldn't present a problem...I got a little confused since I was accidentally running an older x64 version of Node on my M1 (and am running Lando from source), but this is not a normal use case.

**Pull request merged**
